# Site settings
title: OdobGames
email: 13odob27@gmail.com
url: https://github.com/OdobGames/OdobGames
description: "A Indie Game Company OdobGames, making games for everyone!"
keywords: "OdobGames, Games, Indie, Unity, Godot, Engine, Company, HeartTale"
skills: "Indie Game Company"
meta_author: Odob Games

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5F4B6B #80B3FF
  primary-rgb: "95,65,107" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: OdobGames
  location: GamingWorld
  social: Socials
  credits: Oscar Ordoñez

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: playstore
    url: https://play.google.com/store/apps/dev?id=6919392884455431395
  - title: linkedin
    url: www.linkedin.com/in/oscarordoñez
  - title: github
    url: https://github.com/OdobGames

# Postal address (add as many lines as necessary)
address:
  - line: In your Heart :3
  - line: <3

# Credits content
credits: 'Oscar Ordoñez founder of OdobGames Company'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
